# Werkcollege-opdrachten Week 1.3

## Dependencies importeren

Kopieer in het codeblok hieronder van het vorige werkcollege de import-code voor de dependencies die het vaakst worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
Zet eventuele warnings uit.

In [1]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

Zet de volgende bestanden in een makkelijk te vinden map, als je dat nog niet gedaan hebt:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

## Databasetabellen inlezen

Kopieer in het codeblok hieronder van het vorige werkcollege de code om een connectie met het bestand go_sales.sqlite te maken.

In [2]:
sales = sqlite3.connect("../../Database/go_sales.sqlite")

Lees van de ingelezen go_sales-database te volgende tabellen in met behulp van "SELECT * FROM *tabel*".
- product
- product_type
- product_line
- sales_staff
- sales_branch
- retailer_site
- country
- order_header
- order_details
- returned_item
- return_reason

In [3]:
product1 = pd.read_sql("SELECT * FROM product", sales)
product_type1 = pd.read_sql("SELECT * FROM product_type", sales)
product_line1 = pd.read_sql("SELECT * FROM product_line", sales)
sales_staff1 = pd.read_sql("SELECT * FROM sales_staff", sales)
sales_branch1 = pd.read_sql("SELECT * FROM sales_branch", sales)
retailer_site1 = pd.read_sql("SELECT * FROM retailer_site", sales)
country1 = pd.read_sql("SELECT * FROM country", sales)
order_header1 = pd.read_sql("SELECT * FROM order_header", sales)
order_details1 = pd.read_sql("SELECT * FROM order_details", sales)
returned_item1 = pd.read_sql("SELECT * FROM returned_item", sales)
return_reason1 = pd.read_sql("SELECT * FROM return_reason", sales)

Krijg je een "no such table" error? Dan heb je misschien met .connect() per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br> <u>Let op:</u> lees eventueel de informatie uit het vorige werkcollege nog eens goed door.

Als je tijdens onderstaande opdrachten uit het oog verliest welke tabellen er allemaal zijn, kan je deze Pythoncode uitvoeren:

In [5]:
sql_query = "SELECT * FROM sqlite_master WHERE type='table';"
#Vul dit codeblok verder in
pd.read_sql(sql_query, sales)
#Op de puntjes hoort de connectie naar go_sales óf go_staff óf go_crm te staan.

,type,name,tbl_name,rootpage,sql
0,table,country,country,480,"CREATE TABLE ""country"" (\n\t""COUNTRY_CODE""\tIN..."
1,table,order_details,order_details,11,"CREATE TABLE ""order_details"" (\n\t""ORDER_DETAI..."
2,table,order_header,order_header,24,"CREATE TABLE ""order_header"" (\n\t""ORDER_NUMBER..."
3,table,order_method,order_method,27,"CREATE TABLE ""order_method"" (\n\t""ORDER_METHOD..."
4,table,product,product,28,"CREATE TABLE ""product"" (\n\t""PRODUCT_NUMBER""\t..."
5,table,product_line,product_line,17,"CREATE TABLE ""product_line"" (\n\t""PRODUCT_LINE..."
6,table,product_type,product_type,10,"CREATE TABLE ""product_type"" (\n\t""PRODUCT_TYPE..."
7,table,retailer_site,retailer_site,18,"CREATE TABLE ""retailer_site"" (\n\t""RETAILER_SI..."
8,table,return_reason,return_reason,30,"CREATE TABLE ""return_reason"" (\n\t""RETURN_REAS..."
9,table,returned_item,returned_item,31,"CREATE TABLE ""returned_item"" (\n\t""RETURN_CODE..."
10,table,sales_branch,sales_branch,2,"CREATE TABLE ""sales_branch"" (\n\t""SALES_BRANCH..."
11,table,sales_staff,sales_staff,3,"CREATE TABLE ""sales_staff"" (\n\t""SALES_STAFF_C..."

Let op! Voor alle onderstaande opdrachten mag je <u>alleen Python</u> gebruiken, <u>geen SQL!</u>

## Selecties op één tabel zonder functies

Geef een overzicht met daarin de producten en hun productiekosten waarvan de productiekosten lager dan 100 dollar en hoger dan 50 dollar ligt. (2 kolommen, 23 rijen)

In [6]:
# door de & teken krijg je rijen waar de koste tussen 50 en 100 liggen
filtered = product1[(product1['PRODUCTION_COST'] > 50) & (product1['PRODUCTION_COST'] < 100)]

filtered[['PRODUCT_NAME', 'PRODUCTION_COST']]

                        PRODUCT_NAME  PRODUCTION_COST
5          TrailChef Deluxe Cook Set            85.11
7             TrailChef Double Flame            75.00
16                   Hibernator Lite            60.00
17                        Hibernator            86.00
19   Hibernator Self - Inflating Mat            78.55
22               Hibernator Camp Cot            65.33
23      Canyon Mule Climber Backpack            62.50
45           Granite Climbing Helmet            52.86
47             Husky Harness Extreme            55.00
57                    Granite Hammer            57.13
68                         Polar Ice            73.33
69                      Polar Sports            80.00
70                        Polar Wave            60.00
71                     Polar Extreme            72.50
74                      Edge Extreme            80.00
77                         Seeker 35            79.19
78                         Seeker 50            92.58
79                    Seeker Extreme            94.12
82                    Glacier Deluxe            56.25
83                       Glacier GPS            78.55
109                Blue Steel Putter            60.00
110            Blue Steel Max Putter            81.80
113              Course Pro Golf Bag            80.00

Geef een overzicht met daarin de producten en hun marge waarvan de marge lager dan 20 % of hoger dan 60 % ligt. (2 kolommen, 7 rijen)

In [7]:
# | = of
filtered_margin = product1[(product1['MARGIN'] < 0.20) | (product1['MARGIN'] > 0.60)]

filtered_margin[['PRODUCT_NAME', 'MARGIN']]

                    PRODUCT_NAME  MARGIN
20                Hibernator Pad    0.17
23  Canyon Mule Climber Backpack    0.17
85             BugShield Natural    0.67
86               BugShield Spray    0.67
87         BugShield Lotion Lite    0.70
88              BugShield Lotion    0.63
89             BugShield Extreme    0.63

Geef een overzicht met daarin de landen waar met francs wordt betaald. Sorteer de uitkomst op land.  (1 kolom, 3 rijen)

In [8]:
filter_op_francs = country1[country1['CURRENCY_NAME'] == 'francs']

filter_op_francs[['COUNTRY']]

        COUNTRY
0        France
7   Switzerland
15      Belgium

Geef een overzicht met daarin de verschillende introductiedatums waarop producten met meer dan 50% marge worden geïntroduceerd (1 kolom, 7 rijen)

In [9]:
filtered_margin_50 = product1[product1['MARGIN'] > 0.50]

#drop_duplicates() haald de dubbelen er uit waardoor je de 7 rijen krijgt
filtered_margin_50[['INTRODUCTION_DATE']].drop_duplicates()

    INTRODUCTION_DATE
66         2000-10-26
85         1995-02-15
101        2003-12-10
103        2003-12-18
104        2003-12-27
106        2004-01-13
110        2003-12-15

Geef een overzicht met daarin het eerste adres en de stad van verkoopafdelingen waarvan zowel het tweede adres als de regio bekend is (2 kolommen, 7 rijen)

In [10]:
#notna() = notnull()
wel_tweede_addres = sales_branch1[(sales_branch1['ADDRESS2'].notna()) & (sales_branch1['REGION'].notna())]

wel_tweede_addres[['ADDRESS1', 'CITY']]

                            ADDRESS1              CITY
2                Singelgravenplein 4         Amsterdam
13  Prol. Paseo de la Reforma No. 51  Distrito Federal
14               202-2-3 Hyakunincho             Tokyo
15                     543-225 Asahi        Osaka City
16                  2315 Queen's Ave         Melbourne
18             Avenida Paulista, 333         São Paulo
24                    3 Albany Court        Birmingham

Geef een overzicht met daarin de landen waar met dollars (dollars of new dollar) wordt betaald. Sorteer de uitkomst op land. (1 kolom, 4 rijen)

In [11]:
filtered_op_dollars = country1[(country1['CURRENCY_NAME'] == 'dollars') | (country1['CURRENCY_NAME'] == 'new dollar')]

filtered_op_dollars[['COUNTRY']]

          COUNTRY
2   United States
3          Canada
11         Taiwan
14      Australia

Geef een overzicht met daarin beide adressen en de stad van vestigingen van klanten waarvan de postcode begint met een ‘D’ (van duitsland). Filter op vestigingen die een tweede adres hebben. (3 kolommen, 2 rijen)

In [13]:
#str[...] = gebruik je als je bijvoorbeeld het woord met de leter D wil laten beginen
#str.contains() = gebrik je als de leter aleen in het woord moet ziten
filterde_klanten = retailer_site1[(retailer_site1['POSTAL_ZONE'].str[0] == 'D') & (retailer_site1['ADDRESS2'].notna())]

filterde_klanten[['ADDRESS1', 'ADDRESS2', 'CITY']]

            ADDRESS1       ADDRESS2       CITY
31  Röntgenstraße 90  3. Tür rechts  Frankfurt
59   Grubesallee 141       4. Stock    Hamburg

## Selecties op één tabel met functies

Geef het totaal aantal producten dat is teruggebracht (1 waarde)

In [14]:
sumproduct = returned_item1['RETURN_QUANTITY'].sum() # sum() = telt alle waarden in de kolom bij elkaar op
#pd.DataFrame zet de sum in een tabel met een toepasende naam
pd.DataFrame({'Total teruggebrachte producten': [sumproduct]})

   Total teruggebrachte producten
0                           11908

Geef het aantal regio’s waarin verkoopafdelingen gevestigd zijn. (1 waarde)

In [15]:
#.nunique() teld aantal unieke waarden in elke kolom op
#.dropna() verwijdert alle rijen/kolommen waar de warden null/NaN is
m1 = sales_branch1['REGION'].dropna().nunique()
pd.DataFrame({'total aantal verschilende regios': [m1]})

   total aantal verschilende regios
0                                15

Maak 3 variabelen:
- Een met de laagste
- Een met de hoogste
- Een met de gemiddelde (afgerond op 2 decimalen)

marge van producten (3 kolommen, 1 rij)

In [16]:
laag = product1['MARGIN'].min() #min() is voor de laagste te vinden
hoog = product1['MARGIN'].max() #max() is voor de hoogste te vinden
gemideld = product1['MARGIN'].mean() #mean() is het gemidelde
gemideldafgerond = gemideld.round(2) #round(...) rond het af op 2 decimalen

tabel = {
    'laagste marge': [laag],
    'hoogste marge': [hoog],
    'gemiddelde marge': [gemideldafgerond]
}

pd.DataFrame(tabel)

   laagste marge  hoogste marge  gemiddelde marge
0           0.17            0.7               0.4

Geef het aantal vestigingen van klanten waarvan het 2e adres niet bekend is (1 waarde)

In [17]:
#isna() = kijkt of het null/NaN is, en Sum() teld dit weer op
vestigingen = retailer_site1['ADDRESS2'].isna().sum()
pd.DataFrame({'Aantal klanten waar 2de adres niet bekend is': [vestigingen]})

   Aantal klanten waar 2de adres niet bekend is
0                                           286

Geef de gemiddelde kostprijs van de verkochte producten waarop korting (unit_sale_price < unit_price) is verleend (1 waarde)

In [18]:
kostprijs = order_details1[order_details1['UNIT_SALE_PRICE'] < order_details1['UNIT_PRICE']]
gemideldeKostprijs = kostprijs['UNIT_PRICE'].mean()
pd.DataFrame({'gemiddelde kostprijs': [gemideldeKostprijs]})

   gemiddelde kostprijs
0            204.987422

Geef een overzicht met daarin het aantal medewerkers per medewerkersfunctie (2 kolommen, 7 rijen)

In [19]:
# groupby(...) = groepeert gegevens op basis van 1 of meerdere kolomen
# count() = telt het aantal rijen per groep
sales_staff1.groupby('POSITION_EN', as_index = False)['SALES_STAFF_CODE'].count()

                    POSITION_EN  SALES_STAFF_CODE
0                Branch Manager                19
1              District Manager                 4
2               General Manager                 1
3  Level 1 Sales Representative                13
4  Level 2 Sales Representative                39
5  Level 3 Sales Representative                24
6              Regional Manager                 2

Geef een overzicht met daarin per telefoonnummer het aantal medewerkers dat op dat telefoonnummer bereikbaar is. Toon alleen de telefoonnummer waarop meer dan 4 medewerkers bereikbaar zijn. (2 kolommen, 10 rijen)

In [20]:
aantalmedewerkers = sales_staff1.groupby('WORK_PHONE', as_index = False)['SALES_STAFF_CODE'].count()
antword = aantalmedewerkers[aantalmedewerkers['SALES_STAFF_CODE'] > 4]
antword

             WORK_PHONE  SALES_STAFF_CODE
4     +(44) 121 3505267                 5
10  +(61) 03 2982  4242                 5
11  +31 (0)20 692 93 94                 5
13    +33 1 68 94 52 20                 5
18     1 (206) 292-0012                 5
19     1 (305) 557-4810                 6
20     1 (310) 281-5722                 5
21     1 (403) 232-5986                 5
22     1 (416) 493-5595                 5
23     1 (617) 268-6754                 6

## Selecties op meerdere tabellen zonder functies

Geef een overzicht met daarin het eerste adres en de stad van vestigingen van klanten uit ‘Netherlands’ (2 kolommen, 20 rijen)

In [21]:
merge1 = pd.merge(retailer_site1, country1, left_on = 'COUNTRY_CODE', how = 'inner', right_on = 'COUNTRY_CODE')

smerge = merge1[(merge1['COUNTRY'] == 'Netherlands') &
                (merge1['ADDRESS1'].notna()) &
                (merge1['CITY'].notna())]

smerge[['ADDRESS1', 'CITY']]

                      ADDRESS1          CITY
240                   Beets 36         Beets
241               Perestraat 1      Deventer
242  Laan van Meerdervoort 966      Den Haag
243             Kalfjeslaan 47    Amstelveen
244               Startbaan 11    Amstelveen
245      Noorderspoorsingel 28     Groningen
246              Hogehilweg 13     Amsterdam
247             Spoorstraat 43    Varsseveld
248             Westhavenweg 8     Amsterdam
249              Westzeedijk 4        Muiden
250            Gooiergracht 91         Laren
251            Hoofdstraat 150   Pieterburen
252                Olde Diek 2         Laren
253     Amsterdamsestraatweg 8      Maarssen
254        Krayenhoffstraat 11     Amsterdam
255         Overschiestraat 19     Amsterdam
256              Havenbuurt 12        Marken
257               Duivendaal 1    Wageningen
258              Voorstraat 37  Nieuweschans
259         Stadhouderslaan 18     Rotterdam

Geef een overzicht met daarin de productnamen die tot het producttype ‘Eyewear’ behoren. (1 kolom, 5 rijen)

In [22]:
merge2 = pd.merge(product1, product_type1, left_on = 'PRODUCT_TYPE_CODE', how = 'inner', right_on = 'PRODUCT_TYPE_CODE')

smerge2 = merge2[(merge2['PRODUCT_TYPE_EN'] == 'Eyewear')]

smerge2[['PRODUCT_NAME']]

     PRODUCT_NAME
67      Polar Sun
68      Polar Ice
69   Polar Sports
70     Polar Wave
71  Polar Extreme

Geef een overzicht met daarin alle unieke eerste adressen van klantvestigingen en de voornaam en achternaam van de verkopers die ‘Branch Manager’ zijn en aan deze vestigingen hebben verkocht (3 kolommen, 1 rij)

In [23]:
merge3 = pd.merge(retailer_site1, order_header1, left_on = 'RETAILER_SITE_CODE', how = 'inner', right_on = 'RETAILER_SITE_CODE')
merge4 = pd.merge(sales_staff1, order_header1, left_on = 'SALES_STAFF_CODE', how = 'inner', right_on = 'SALES_STAFF_CODE')

merge5 = pd.merge(merge3, merge4, left_on = 'ORDER_NUMBER', how = 'inner', right_on = 'ORDER_NUMBER')

smerge3 = merge5[(merge5['ADDRESS1'].notna()) & 
                 (merge5['POSITION_EN'] == 'Branch Manager')].drop_duplicates('ADDRESS1')
smerge3[['ADDRESS1', 'FIRST_NAME', 'LAST_NAME']]

                  ADDRESS1 FIRST_NAME LAST_NAME
3658  Alameda Santos, 9876     Bayard     Lopes

Geef een overzicht met daarin van de verkopers hun functie en indien zij iets hebben verkocht de datum waarop de verkoop heeft plaatsgevonden. Laat alleen de verschillende namen van de posities zien van de verkopers die het woord ‘Manager’ in hun positienaam hebben staan. (2 kolommen, 7 rijen)

In [24]:
merge6 = pd.merge(sales_staff1, order_header1, left_on = 'SALES_STAFF_CODE', how = 'left', right_on = 'SALES_STAFF_CODE')

menagers = merge6[(merge6['POSITION_EN'].str.contains('Manager'))].drop_duplicates('POSITION_EN')
dates = merge6[(merge6['POSITION_EN'].str.contains('Manager')) & (merge6['ORDER_DATE'].notna())]
smerge4 = pd.concat([menagers, dates], axis= 0)
smerge4[['POSITION_EN', 'ORDER_DATE']]

           POSITION_EN  ORDER_DATE
0       Branch Manager         NaN
320   Regional Manager         NaN
648   District Manager         NaN
4186   General Manager         NaN
3748    Branch Manager  2024-09-09
3749    Branch Manager  2024-03-13
3750    Branch Manager  2024-01-09

Geef een overzicht met daarin de verschillende namen van producten en bijbehorende namen van producttypen van de producten waarvoor ooit meer dan 750 stuks tegelijk verkocht zijn. (2 kolommen, 9 rijen)

In [25]:
merge7 = pd.merge(product1, order_details1, left_on = 'PRODUCT_NUMBER', how = 'inner', right_on = 'PRODUCT_NUMBER')
merge8 = pd.merge(product1, product_type1, left_on = 'PRODUCT_TYPE_CODE', how = 'inner', right_on = 'PRODUCT_TYPE_CODE')
merge9 = pd.merge(merge7, merge8, left_on = 'PRODUCT_NUMBER', how = 'inner', right_on = 'PRODUCT_NUMBER')

smerge5 = merge9[(merge9['QUANTITY'] > 750) & 
                 (merge9['PRODUCT_NAME_x'].notna())].drop_duplicates('PRODUCT_NAME_x')
smerge5[['PRODUCT_NAME_x', 'PRODUCT_TYPE_EN']]

              PRODUCT_NAME_x    PRODUCT_TYPE_EN
5427                Star Peg              Tents
11452              Firefly 2           Lanterns
28608        BugShield Spray  Insect Repellents
28892  BugShield Lotion Lite  Insect Repellents
29430       BugShield Lotion  Insect Repellents
29442      BugShield Extreme  Insect Repellents
30741         Sun Shelter 15          Sunscreen
31164         Sun Shelter 30          Sunscreen
31775             Sun Shield          Sunscreen

Geef een overzicht met daarin de productnamen waarvan ooit meer dan 40% korting is verleend. De formule voor korting is: (unit_price - unit_sale_price) / unit_price (1 kolom, 8 rijen)

In [26]:
merge10 = pd.merge(product1, order_details1, left_on = 'PRODUCT_NUMBER', how = 'inner', right_on = 'PRODUCT_NUMBER')
merge10['DISCOUNT'] = (merge10['UNIT_PRICE'] - merge10['UNIT_SALE_PRICE']) / merge10['UNIT_PRICE']
smerge6 = merge10[(merge10['DISCOUNT'] > 0.40)]
smerge6[['PRODUCT_NAME']].drop_duplicates('PRODUCT_NAME')

                       PRODUCT_NAME
27830             BugShield Natural
28283               BugShield Spray
28694         BugShield Lotion Lite
29127              BugShield Lotion
29464             BugShield Extreme
30562                Sun Shelter 15
30929                Sun Shelter 30
34441  Hailstorm Titanium Woods Set

Geef een overzicht met daarin de retourreden van producten waarvan ooit meer dan 90% van de aangeschafte hoeveelheid is teruggebracht (return_quantity/quantity). (1 kolom, 3 rijen)

In [27]:
merge11 = pd.merge(returned_item1, order_details1, left_on = 'ORDER_DETAIL_CODE', how = 'inner', right_on = 'ORDER_DETAIL_CODE')
merge12 = pd.merge(return_reason1, returned_item1, left_on = 'RETURN_REASON_CODE', how = 'inner', right_on = 'RETURN_REASON_CODE')
merge13 = pd.merge(merge11, merge12, left_on = 'RETURN_CODE', how = 'inner', right_on = 'RETURN_CODE')

merge13['RETURN_RATIO'] = merge13['RETURN_QUANTITY_x'] / merge13['QUANTITY']
smerge7 = merge13[merge13['RETURN_RATIO'] > 0.90]
smerge7[['RETURN_DESCRIPTION_EN']].drop_duplicates('RETURN_DESCRIPTION_EN')

    RETURN_DESCRIPTION_EN
0  Unsatisfactory product
2   Wrong product shipped
3   Wrong product ordered

## Selecties op meerdere tabellen met functies

Geef een overzicht met daarin per producttype het aantal producten die tot dat producttype behoren. (2 kolommen, 21 rijen)

In [28]:
merge14 = pd.merge(product_type1, product1, left_on = 'PRODUCT_TYPE_CODE', how = 'inner', right_on = 'PRODUCT_TYPE_CODE')
antword1 = merge14.groupby('PRODUCT_TYPE_EN')['PRODUCT_TYPE_CODE'].count().reset_index(name = 'aantal producten')
antword1

         PRODUCT_TYPE_EN  aantal producten
0             Binoculars                 4
1   Climbing Accessories                 7
2           Cooking Gear                10
3                Eyewear                 5
4              First Aid                 5
5       Golf Accessories                 4
6      Insect Repellents                 5
7                  Irons                 4
8                 Knives                 5
9               Lanterns                12
10            Navigation                 4
11                 Packs                 6
12               Putters                 3
13                  Rope                 4
14                Safety                 4
15         Sleeping Bags                 7
16             Sunscreen                 5
17                 Tents                 6
18                 Tools                 6
19               Watches                 5
20                 Woods                 4

Geef een overzicht met daarin per land het aantal vestigingen van klanten die zich in dat land bevinden. (2 kolommen, 21 rijen)

In [30]:
merge15 = pd.merge(country1, retailer_site1, left_on = 'COUNTRY_CODE', how = 'inner', right_on = 'COUNTRY_CODE')

# reset_index() = reset de index (de cijvers helemaal lings)
antword2 = merge15.groupby('COUNTRY')['COUNTRY_CODE'].count().reset_index(name = 'aantal vestigingen')

antword2

           COUNTRY  aantal vestigingen
0        Australia                  10
1          Austria                  10
2          Belgium                  10
3           Brazil                   1
4           Canada                  31
5            China                  10
6          Denmark                   6
7          Finland                   5
8           France                  29
9          Germany                  32
10           Italy                  12
11           Japan                  25
12           Korea                  10
13          Mexico                  10
14     Netherlands                  20
15           Spain                   9
16          Sweden                  12
17     Switzerland                  13
18          Taiwan                  10
19  United Kingdom                  25
20   United States                 101

Geef een overzicht met daarin van de producten behorend tot het producttype ‘Cooking Gear’ per productnaam de totaal verkochte hoeveelheid en de gemiddelde verkoopprijs. Sorteer de uitkomst op totaal verkochte hoeveelheid. (6 kolommen, 10 rijen)

In [ ]:
# Je komt met de bovenstande info niet uit op 6 kolommen maar 4

merge16 = pd.merge(product_type1, product1, left_on = 'PRODUCT_TYPE_CODE', how = 'inner', right_on = 'PRODUCT_TYPE_CODE')
merge17 = pd.merge(order_details1, product1, left_on = 'PRODUCT_NUMBER', how = 'inner', right_on = 'PRODUCT_NUMBER')
merge18 = pd.merge(merge17, merge16, left_on = 'PRODUCT_NUMBER', how = 'inner', right_on = 'PRODUCT_NUMBER')
smerge8 = merge18[merge18['PRODUCT_TYPE_EN'] == 'Cooking Gear']

overzigt = smerge8.groupby('PRODUCT_NAME_x').agg(
    totaal_verkocht =('QUANTITY', 'sum'),
    gemiddelde_verkoopprijs =('UNIT_PRICE', 'mean'),
    product_type=('PRODUCT_TYPE_EN', 'first') #omdat je hierboven het al heb gesorteerd op Cooking Gear is alles het zelfte en gebruik je first
).reset_index()

overzigt.sort_values(by = 'totaal_verkocht', ascending = False)

,PRODUCT_NAME_x,totaal_verkocht,gemiddelde_verkoopprijs,product_type
9,TrailChef Water Bag,36738,6.200716,Cooking Gear
2,TrailChef Cup,27418,7.157326,Cooking Gear
0,TrailChef Canteen,26544,12.210194,Cooking Gear
6,TrailChef Kitchen Kit,22206,22.849400,Cooking Gear
8,TrailChef Utensils,13776,17.836475,Cooking Gear
4,TrailChef Double Flame,12476,137.535088,Cooking Gear
1,TrailChef Cook Set,10878,52.990028,Cooking Gear
5,TrailChef Kettle,8826,12.421525,Cooking Gear
7,TrailChef Single Flame,8504,65.289805,Cooking Gear
3,TrailChef Deluxe Cook Set,3110,124.178425,Cooking Gear

Geef een overzicht met daarin per land de naam van het land, de naam van de stad waar de verkoopafdeling is gevestigd (noem de kolomnaam in het overzicht ‘verkoper’) en het aantal steden waar zich klanten bevinden in dat land (noem de kolomnaam in het overzicht ‘klanten’) (3 kolommen, 29 rijen)

In [33]:
# ik krijg 20 rijen niet 29 rijen

merge19 = pd.merge(country1, sales_branch1, left_on = 'COUNTRY_CODE', how = 'inner', right_on = 'COUNTRY_CODE')
merge20 = pd.merge(country1, retailer_site1, left_on = 'COUNTRY_CODE', how = 'inner', right_on = 'COUNTRY_CODE')
merge21 = pd.merge(merge19, merge20, left_on = 'COUNTRY_CODE', how = 'inner', right_on = 'COUNTRY_CODE')

# agg() = aggregate, samenvattende berekeningen uit te voeren op kolommen
overzigt2 = merge21.groupby('COUNTRY_x').agg(
    verkoper = ('CITY_x', 'first'),
    klanten = ('CITY_y', 'nunique')
).reset_index()

overzigt2[['COUNTRY_x', 'verkoper', 'klanten']]

         COUNTRY_x          verkoper  klanten
0        Australia         Melbourne        6
1          Austria              Wien        9
2          Belgium          Heverlee        8
3           Brazil         São Paulo        1
4           Canada           Calgary       16
5            China          Shanghai        7
6          Finland            Kuopio        5
7           France             Paris       14
8          Germany           Hamburg       18
9            Italy            Milano        9
10           Japan             Tokyo        5
11           Korea             Seoul        6
12          Mexico  Distrito Federal        6
13     Netherlands         Amsterdam       15
14           Spain            Bilbao        5
15          Sweden             Kista       10
16     Switzerland            Zürich        9
17          Taiwan         San Chung        9
18  United Kingdom            London        9
19   United States            Boston       62

## Pythonvertalingen van SUBSELECT en UNION met o.a. for-loops

Geef een overzicht met daarin de voornaam en de achternaam van de medewerkers die nog nooit wat hebben verkocht (2 kolommen, 25 rijen)

In [34]:
# set() = verwijdert automatisch dubbele waardens
order_ids = set(order_header1["SALES_STAFF_CODE"])

# ~ = niet, dus dit filtert de medewerkers zonder verkooporders eruit
medewerkers_zonder_verkoop = sales_staff1[~sales_staff1["SALES_STAFF_CODE"].isin(order_ids)]
resultaat = medewerkers_zonder_verkoop[["FIRST_NAME", "LAST_NAME"]].reset_index(drop = True) 
# reset_index(drop = True) = zorgt ervoor dat de index netjes opnieuw begint bij 0, zonder de oude index mee te nemen
resultaat

   FIRST_NAME      LAST_NAME
0       Denis           Pagé
1        Else         Mörike
2       Frank          Fuchs
3       Fritz         Hirsch
4        Jörg          Kunze
5       Maria      Iacobucci
6        Kick        Kalkman
7       Karin      Bergström
8       Sally          White
9       Frank        Bretton
10    Georges  Saint-Germain
11       Alex      Rodriguez
12   Samantha          Floyd
13      Julie          Olsen
14      Corey         Wright
15    Estelle        Johnson
16       Greg        Belding
17      Julie        Béchard
18      Lucía          Reyna
19     Kazumi        Uragome
20      Alice         Walter
21     Walter         Taylor
22   Penelope        Tamrine
23      Polly         Linton
24      Gracy        Gellens

Geef een overzicht met daarin het aantal producten waarvan de marge lager is dan de gemiddelde marge van alle producten samen. Geef in het overzicht tevens aan wat de gemiddelde marge is van dit aantal producten waarvan de marge lager dan de gemiddelde marge van alle producten samen is. (1 kolom, 2 rijen)

In [35]:
gemidelde_marge = product1["MARGIN"].mean()

lager_dan_gem = product1[product1["MARGIN"] < gemidelde_marge]

overzigt3 = pd.DataFrame({
    "Waarde": [
        lager_dan_gem.shape[0],
        lager_dan_gem["MARGIN"].mean()
    ]
}, index=["Aantal producten", "Gemiddelde marge"])
# index=[...] = zet ik de rijlabels mee
overzigt3

                     Waarde
Aantal producten  59.000000
Gemiddelde marge   0.292203

Geef een overzicht met daarin de namen van de producten die voor meer dan 500 (verkoopprijs) zijn verkocht maar nooit zijn teruggebracht. (1 kolom, 13 rijen)

In [36]:
verkocht_duur = order_details1[order_details1["UNIT_PRICE"] > 500]
teruggestuurde_ids = set(returned_item1["ORDER_DETAIL_CODE"])
niet_teruggebracht = verkocht_duur[~verkocht_duur["ORDER_DETAIL_CODE"].isin(teruggestuurde_ids)]
niet_teruggebracht_met_naam = niet_teruggebracht.merge(
    product1[["PRODUCT_NUMBER", "PRODUCT_NAME"]],
    on="PRODUCT_NUMBER",
    how="left"
)

resultaat2 = niet_teruggebracht_met_naam[["PRODUCT_NAME"]].drop_duplicates()
resultaat2 = resultaat2.reset_index(drop=True)
resultaat2

                         PRODUCT_NAME
0                           Star Dome
1                        Star Gazer 2
2                        Star Gazer 3
3                        Star Gazer 6
4               Hailstorm Steel Irons
5            Hailstorm Titanium Irons
6          Lady Hailstorm Steel Irons
7       Lady Hailstorm Titanium Irons
8        Hailstorm Titanium Woods Set
9           Hailstorm Steel Woods Set
10  Lady Hailstorm Titanium Woods Set
11     Lady Hailstorm Steel Woods Set
12                     Husky Rope 200

Geef een overzicht met daarin per (achternaam van) medewerker of hij/zij manager is of niet, door deze informatie toe te voegen als extra 'Ja/Nee'-kolom.<br>
Hint: gebruik een for-loop waarin je o.a. bepaalt of het woord 'Manager' in de functie (position_en) staat. (2 kolommen, 102 rijen).

In [37]:
# hier maak ik een kopie van de tabel, zodat ik er mee kan werken zonder de originele aan te passen
df = sales_staff1.copy()
is_manager = []


for functie in df["POSITION_EN"]:
    if "manager" in functie.lower():
        is_manager.append("Ja")
    else:
        is_manager.append("Nee")

df["Is manager"] = is_manager
resultaat3 = df[["LAST_NAME", "Is manager"]]
resultaat3

     LAST_NAME Is manager
0         Pagé         Ja
1       Michel        Nee
2     Clermont        Nee
3       Jauvin        Nee
4    Wiesinger        Nee
..         ...        ...
97    Laermans        Nee
98     De Crée        Nee
99     Lattrez        Nee
100  Seefelder        Nee
101     Grüner        Nee

[102 rows x 2 columns]

Met de onderstaande code laat je Python het huidige jaar uitrekenen.

In [38]:
from datetime import date
date.today().year

2026

Met de onderstaande code selecteer je op een bepaald jaartal uit een datum.

In [39]:
from datetime import datetime

date_str = '16-8-2013'
date_format = '%d-%m-%Y'
date_obj = datetime.strptime(date_str, date_format)

date_obj.year

2013

Geef met behulp van bovenstaande hulpcode een overzicht met daarin op basis van het aantal jaar dat iemand in dienst is of een medewerker ‘kort in dienst’ (minder dan 30 jaar in dienst) of een ‘lang in dienst’ (groter dan gelijk aan 30 jaar in dienst) is. Geef daarbij per medewerker in een aparte kolom zowel ‘kort in dienst’ als ‘lang in dienst’ aan. Gebruik (wederom) een for-loop.<br>
(2 kolommen, 102 rijen)

In [40]:
#date.today() = geeft de datum van vandaag
#.year = haalt aleen het jaartal uit
huidig_jaar = date.today().year
df = sales_staff1.copy()
dienstverband_status = []

for datum_str in df["DATE_HIRED"]:
    # strptime() = zet de tekst om naar een datum
    date_obj = datetime.strptime(datum_str, "%Y-%m-%d")
    # berekent hoeveel jaar in dienst
    in_dienst_jaren = huidig_jaar - date_obj.year

    if in_dienst_jaren >= 30:
        status = "Lang in dienst"
    else:
        status = "Kort in dienst"
    
    dienstverband_status.append(status)

df["Dienstverband"] = dienstverband_status
resultaat4 = df[["LAST_NAME", "Dienstverband"]]
resultaat4

     LAST_NAME   Dienstverband
0         Pagé  Lang in dienst
1       Michel  Lang in dienst
2     Clermont  Kort in dienst
3       Jauvin  Kort in dienst
4    Wiesinger  Kort in dienst
..         ...             ...
97    Laermans  Kort in dienst
98     De Crée  Kort in dienst
99     Lattrez  Kort in dienst
100  Seefelder  Kort in dienst
101     Grüner  Kort in dienst

[102 rows x 2 columns]